language: python

branches:
  only:
    - master
  - javascript-refactoring

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements_dev.txt

script:
  - flake8
  - cd tests/
  - coverage run --source=../source -m pytest

after_success:
  - coveralls
