dist: "trusty"

language: python

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - sudo pip3 install -r requirements_dev.txt

script:
  - flake8
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sudo apt-get install chromium-browser
  - sudo chmod a+x ./tests/chromedriver
  - sudo coverage run --source=/eNMS -m pytest

after_success:
  - coveralls
