language: python

branches:
  only:
    - master

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

branches:
  only:
  - master

install:
  - pip install -r requirements_dev.txt

script:
  - flake8
  - cd tests/
  - coverage run --source=../source -m pytest

after_success:
  - coveralls
